# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: cert-manager-webhook-ovh actions

on:
  push:
    tags:
      - 0*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  helm-test:
    runs-on: ubuntu-latest
    steps:
      - name: harden-runner
        uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: audit
      - name: checkout-code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: set-up-helm
        uses: azure/setup-helm@v4.3.1
        with:
          version: v4.1.1

      - name: install-helm-unittest-plugin
        run: |
          make install-helm-unittest

      - name: run-helm-unittest
        run: |
          make helm-unittest

  build-and-push-image:
    runs-on: ubuntu-latest

    needs:
      - helm-test

    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout-code
        uses: actions/checkout@v6

      - name: set-up-qemu
        uses: docker/setup-qemu-action@v4

      - name: set-up-docker-buildx
        uses: docker/setup-buildx-action@v4

      - name: log-in-to-container-registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: extract-metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{raw}}

      - name: build-and-push-container-image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          platforms: linux/arm64,linux/arm/v7,linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  chart-release:
    needs:
      - build-and-push-image
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: checkout-code
        uses: actions/checkout@v6
        with:
          # # Fetch entire history. Required for chart-releaser; see https://github.com/helm/chart-releaser-action/issues/13#issuecomment-602063896
          fetch-depth: 0

      - name: set-up-helm
        uses: azure/setup-helm@v4.3.1
        with:
          version: v4.1.1

      - name: create-chart-package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p tmp/packages
          cp charts/cert-manager-webhook-ovh/README.md tmp/
          cp LICENSE charts/cert-manager-webhook-ovh/
          cp README.md charts/cert-manager-webhook-ovh/
          helm package --destination tmp/packages/ charts/cert-manager-webhook-ovh/
          cp charts/cert-manager-webhook-ovh/Chart.yaml tmp/
          cp artifacthub-repo.yml tmp/

      - name: log-in-to-oci-registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: publish-chart-to-oci-registry
        run: |
          for PKG in tmp/packages/*.tgz; do
            if [ ! -s "$PKG" ]; then
              echo "Package archive $PKG is empty. Failing the release process."
              exit 1
            fi
            echo "Pushing $PKG to OCI registry ${{ env.REGISTRY }}/${{ github.repository_owner }}/charts"
            helm push "$PKG" oci://${{ env.REGISTRY }}/${{ github.repository_owner }}/charts
          done

      - name: upload-artifacts
        uses: actions/upload-artifact@v7
        with:
          name: chart-archive
          path: tmp/

      - name: gh-pages-checkout-code
        uses: actions/checkout@v6
        with:
          ref: 'gh-pages'
          # Fetch entire history. Required for chart-releaser; see https://github.com/helm/chart-releaser-action/issues/13#issuecomment-602063896
          fetch-depth: 0

      - name: gh-pages-download-artifacts
        uses: actions/download-artifact@v8
        with:
          name: chart-archive
          path: tmp

      - name: gh-page-configure-git
        shell: bash
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: gh-page-index-chart-repo
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          test -d packages || mkdir packages
          gh release upload "$GITHUB_REF_NAME" tmp/packages/*
          mv tmp/packages/* packages/
          mv tmp/Chart.yaml ./
          mv tmp/artifacthub-repo.yml ./
          mv tmp/README.md ./
          helm repo index --url "https://$GITHUB_ACTOR.github.io/$(echo "$GITHUB_REPOSITORY" | cut --delimiter / --fields=2)" .
          git add README.md artifacthub-repo.yml index.yaml packages/
          git status
          git commit -m "Publish $GITHUB_REF_NAME"
          git push origin gh-pages
