name: Tests on Pull Requests

on:
  push:
    branches:
      - main
  pull_request: {}

permissions:
  contents: read

jobs:
  helm-test:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v5.0.0

      - name: Install Golang unit tests dependencies
        run: |
          make install-go-tests

      - name: Install Helm Chart unittest plugin
        run: |
          make install-helm-unittests

      - name: Run the Golang unit tests
        run: |
          make go-tests

      - name: Run the Helm Chart unit tests
        run: |
          make helm-unittests

      - name: Run the Helm Chart lint
        run: |
          make helm-lint
